# Generated by Django 5.0 on 2023-12-09 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Store.colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Store.memory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
